### ISSUE TITLE
gdalwarp is creating a thin band of very high values at the easternmost extent

### ISSUE THREAD

**Issue by sruzzante** [JoshOBrien/gdalUtilities#10]
When I run gdalwarp with function = "sum" it creates a single column at the easternedge of the output raster with very large values. It seems that the values in that column are equal the sum of all the pixels at that latitude. I do not get this error when I run gdalwarp from the OSGeo4W command line. It's possible gdalUtilities is using an older version of gdal, but I don't know how to check this.

Here's my command:

`gdalUtilities::gdalwarp(srcfile = in.tif",
                        dstfile = "out.tif",
                        s_srs = "EPSG:4326",
                        t_srs = "EPSG:4326",
                        tr= c(0.1,0.1),
                        te = c(-180,-56,180,84),
                        r = "sum",
                        overwrite = TRUE)
`
And here is the result:

![image](https://user-images.githubusercontent.com/93397896/222619029-0de062c5-67c4-40a7-af03-8db685b2839a.png)

I am using a gridded population product: https://sedac.ciesin.columbia.edu/data/set/popdynamics-1-km-downscaled-pop-base-year-projection-ssp-2000-2100-rev01

**Comment by JoshOBrien** [comment]
@sruzzante I'm not sure what's causing this issue. To help me debug, would you also share the direct command-line call to gdalwarp that does work for you?

To check which GDAL version is being used by **gdalUtilities**  (`3.5.2` on my machine), you can do `sf::sf_extSoftVersion()`.

**Comment by JoshOBrien** [comment]
@sruzzante I just downloaded the data at the link you provide, ran this command, and got results more like what I think you were expecting. Would you double check your code and also include the results of `sessionInfo()` from a session in which you get those wonky results?

```r
library(gdalUtilities)
library(raster)

in_tif <- "baseYr_rural_2000.tif"
out_tif <- "out.tif"
gdalwarp(srcfile = in_tif, dstfile = out_tif, s_srs = "EPSG:4326", t_srs = "EPSG:4326", 
                tr= c(0.1,0.1), te = c(-180,-56,180,84), r = "sum", overwrite = TRUE)
r <- raster(in_tif)
plot(r)
```
![world](https://user-images.githubusercontent.com/3478309/222744436-4e1e8e32-7f0a-42df-b460-e12b8ac4859f.png)

**Comment by sruzzante** [comment]
Thanks Josh.

To be able to see the one-pixel-wide band in R's plot window, I had to crop to a smaller extent:

```
library(gdalUtilities)
library(raster)
in_tif <- "ssp2_rural_2010.tif"
out_tif <- "out.tif"
gdalwarp(srcfile = in_tif, dstfile = out_tif, s_srs = "EPSG:4326", t_srs = "EPSG:4326", 
         tr= c(0.1,0.1), te = c(-180,-56,180,84), r = "sum", overwrite = TRUE)
r <- raster(out_tif)
r<- raster::crop(r,extent(150,180,0,45))
plot(r)
```

Just a note, in your code it looks like you are replotting the original data.

Looks like my installation of gdalUtilities is also using 3.5.2.

The direct command line call (using GDAL 3.6.2) that worked is: 

`gdalwarp ssp2_rural_2010.tif ssp2_rural_2010_06arcmin_sumb.tif -tr 0.1 0.1 -r sum -te -180 -56 180 84`


Here's my sessionInfo too:

R version 4.2.1 (2022-06-23 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default

locale:
[1] LC_COLLATE=English_Canada.utf8  LC_CTYPE=English_Canada.utf8    LC_MONETARY=English_Canada.utf8
[4] LC_NUMERIC=C                    LC_TIME=English_Canada.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] raster_3.6-11       sp_1.5-1            gdalUtilities_1.2.3

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.9         rstudioapi_0.14    magrittr_2.0.3     units_0.8-0        tidyselect_1.2.0   lattice_0.20-45   
 [7] R6_2.5.1           rlang_1.0.6        fansi_1.0.3        plyr_1.8.7         dplyr_1.0.10       tools_4.2.1       
[13] rgdal_1.6-3        grid_4.2.1         KernSmooth_2.23-20 utf8_1.2.2         terra_1.6-47       cli_3.4.1         
[19] e1071_1.7-11       DBI_1.1.3          class_7.3-20       assertthat_0.2.1   tibble_3.1.8       lifecycle_1.0.3   
[25] sf_1.0-9           vctrs_0.5.1        codetools_0.2-18   glue_1.6.2         proxy_0.4-27       compiler_4.2.1    
[31] pillar_1.8.1       generics_0.1.3     classInt_0.4-8     pkgconfig_2.0.3

**Comment by sruzzante** [comment]
Hi Josh,

I just replicated the error from the command line with an older version of GDAL. The release notes for GDAL 3.6.1 include a bugfix for the problem:

gdalwarp: fix artifacts around antimeridian for average/mode/min/max/med/q1/q3/sum/rms resampling (#6478)

https://github.com/OSGeo/gdal/blob/v3.6.1/NEWS.md

Thanks for your help!

**Comment by JoshOBrien** [comment]
@sruzzante Glad you figured that out! 

FWIW, the plot I displayed actually was of the outputted tif. (The code I copied was what was incorrect in showing `r <- raster(in_tif)` instead of `r <- raster(out_tif)`, which is the raster that the plot shows.)

**Comment by JoshOBrien** [comment]
Closing, as this is in issue with the particular version of GDAL used by **sf**. Once it updates to GDAL 3.6.1 or greater, the upstream fix will propagate down to the functionality of this package.
