### ISSUE TITLE
gdalinfo does not resolve tilde

### ISSUE THREAD

**Issue by floriandeboissieu** [JoshOBrien/gdalUtilities#12]
Thanks for this useful package in prevision of future retirement of rgdal and rgeos.

While using function `gdalinfo` , I noticed that it was unable to resolve/expand "~" for user's home directory, at least on Ubuntu 22.04.

Example (tested on Ubuntu 22.04 only):
```r
image <- system.file("extdata", "europe.tif", package="gdalUtilities")
image_copy <- file.path("~", basename(image))
file.copy(image, image_copy)
info <- gdalUtilities::gdalinfo(image_copy)
if(length(info)==0)
  warning("It should not be character(0)")

gdalUtilities::gdalinfo(path.expand(image_copy))
# returns the good info

# remove image file copy
file.remove(image_copy)
```

It would be nice to have the tilde expanded automatically as it is the usual behavior in R.

Also, if file does not exists, gdalinfo just returns a `NULL` result. I think it would be expected to send an file not found error.

**Comment by JoshOBrien** [comment]
Hi Florian,

Your suggestion regarding the tilde seems reasonable, but I haven't fully thought through whether there might be unforeseen consequences on any of the OS's R supports. I'm inclined to leave specification of the tilde-free path to the user (which is just a matter of doing `normalizePath()` to any paths that need it).

I also agree it'd be nice to have a 'file not found error', though I'm not sure (without delving further) how or whether we can get that info from the function's underlying call to `sf::gdalutils()`. If you see how and share that with me, I'd definitely be open to modifying the functions in my package to return more informative error information on failure.
