### ISSUE TITLE
Caught segfalt error with gdalwarp

### ISSUE THREAD

**Issue by mcgregorian1** [JoshOBrien/gdalUtilities#13]
When I try to run `gdalwarp` in R (conda environment in VSCode), I get the following. After looking up the error I thought it might be due to available memory or the packages, but the former was fine and for the latter I only had this package plus `terra` loaded. I've gotten this error it seems sporadically as well (i.e. a few days ago I had no issue running). 

I tried simply using `dryrun=TRUE` and then running gdal directly using `system()`, which runs with no issue. This makes me think there's something in the package or `gdalUtilities::gdalwarp()` function that's interfering, but I'm not sure what it could be.

```
 *** caught segfault ***
address 0xc, cause 'invalid permissions'

Traceback:
 1: CPL_gdalwarp(source, destination, options, oo, doo, config_options,     quiet, "-overwrite" %in% options)
 2: gdal_utils("warp", source = srcfile, destination = dstfile, options = opts,     config_options = config_options)
 3: gdalwarp(srcfile = f[X], dstfile = outPath, t_srs = "EPSG:32617",     te = c(extCommon[1], extCommon[3], extCommon[2], extCommon[4]),     tr = c(resMin, resMin), tap = TRUE, r = "cubic", overwrite = TRUE,     dryrun = FALSE)
 4: FUN(X[[i]], ...)
 5: lapply(X = X, FUN = FUN, ...)
 6: sapply(1:length(orth$f), standardizeOrthos, f = orth$f, orthos = orth$orthos,     pathOriginal, pathStandard, extCommon, resMin)

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
Selection: 1
R is aborting now ...
zsh: segmentation fault  R
```

**Comment by JoshOBrien** [comment]
@mcgregorian1 I can't reproduce the error without the files and commands you're using. In any case, based on the traceback you included,  it looks like the issue will likely arise from something upstream of my package (i.e. either GDAL itself, or the `sf::gdal_utils()` command for which `gdalUtilities::gdalwarp()` is just a wrapper).

Are you able to share small reproducible example with a file and a command that produces the reported segfault behavior?

**Comment by mcgregorian1** [comment]
Sorry for the delay! Just tested it again and when separating out the call (and isolating the variables) it is working without issue. From this I agree then it's probably something to do with how my function is set-up and interacting with the call to `sf`. At any rate, `gdalwarp()` helps set the command for sending directly to terminal, so at least there's a workaround.

**Comment by JoshOBrien** [comment]
@mcgregorian1 Super. Thanks for following up with that info.
