### ISSUE TITLE
Passing missing argument from function to function

### ISSUE THREAD

**Issue by earthcli** [JoshOBrien/gdalUtilities#5]
I want to wrap the gdal functions in a function with some special default parameters, like below:

myfun<- function(input,out="out.tif",projwin=NULL,...){
   if(is.null(projwin) ) projwin=substitute()
  gdalUtilities::gdal_translate(input, dst_dataset=out, projwin=projwin,...)
}

but it does not work with an error : Error in FUN(X[[i]], ...) : argument "val" is missing, with no default
I can work aroud by:
    if(missing(projwin)){
      gdalUtilities::gdal_translate(fname,dst_dataset=out,...)
    }else{
      gdalUtilities::gdal_translate(fname,dst_dataset=out,projwin=projwin)
    }
But it would be not efficient if there is more parameters for cycling.
Would you please tell me what is the right way?

**Comment by JoshOBrien** [comment]
Hello. From your code, I can't figure out what you are wanting to do. What, for example, is the point of setting the default value of `projwin` to `NULL` rather than just leaving it out of your function's formal argument list altogether?

It seems, though, like you've got a general question about how to set defaults and pass along arguments via an R functions. If I'm wrong, and this is behavior that only affects you when calling `gdal_translate`, can you construct a reproducible example, perhaps using one of the spatial files shipped with my package (like the file `"europe.tif"` used in the examples for `?gdal_translate`)?

**Comment by earthcli** [comment]
@JoshOBrien Thanks for your quick response. For example, some times I need to wrap a bounary or extent parameter with my function, see as below:
`
myfun<- function(input,out="out.tif",projwin=NULL,extent=NULL,...){
  require(gdalUtilities)
  if(is.null(projwin)){
    if(!is.null(extent)){
      projwin=c(extent@xmin,extent@ymax,extent@xmax,extent@ymin)
    }else{
      projwin=substitute() #setting projwin as missing parameter 
    }

  }
  message(projwin)
  message(missing(projwin))
  gdalUtilities::gdal_translate(input, dst_dataset=out, projwin=projwin,...)
}

input <- system.file("external/tahoe_lidar_bareearth.tif",package = "gdalUtils")
extent=new("Extent", xmin = 395293.868917215, xmax = 845871.684498264, 
                     ymin = 3308607.49938524, ymax = 3589495.10978995)
myfun(input,out="test.tif")
myfun(input,out="test1.asc",extent=extent)
`
So, what is the correct way to set a missing parameter as projwin et al in my function body?
Thanks.

**Comment by JoshOBrien** [comment]
I'd probably prepare all of the arguments that need special handling, collecting them in a list, and then use `do.call()` to pass them in to `gdal_translate()`, like so:

```r
library(gdalUtilities)

myfun<- function(input, out="out.tif", ..., projwin, extent){
    require(gdalUtilities)
    args <- list(input, out)
    ## If extent or projwin supplied, add projwin to args
    if(missing(projwin)){
        if(!missing(extent)){
            args[["projwin"]] <- c(extent@xmin,extent@ymax,extent@xmax,extent@ymin)
        }
    } else {
        args[["projwin"]] <- projwin
    }
    ## Call gdal_translate()
    do.call(gdal_translate, c(args, ...))
}

input <- system.file("external/tahoe_lidar_bareearth.tif",package = "gdalUtils")
ext1 <- extent(raster(input))
ext2 <- ext1 * 0.5
myfun(input, out = "test1.tif")
myfun(input, out = "test2.tif", extent = ext2)

```

Does this help?

**Comment by earthcli** [comment]
@JoshOBrien Thanks. This is exactly I am finding. It also inspired me to write other functions like this. 
Just fixed with args <- list(src_dataset=input, dst_dataset=out).
Many thanks.

**Comment by JoshOBrien** [comment]
You bet. Glad that helped.
