### ISSUE TITLE
package archived on CRAN - is it still maintained?

### ISSUE THREAD

**Issue by achubaty** [JoshOBrien/gdalUtilities#8]
Hello, we depend on your package and wanted to check if you plan to release an updated version for CRAN soon.

**Comment by JoshOBrien** [comment]
I think you may have confused my package, *gdalUtilities*, which is actively maintained and currently [available on CRAN](https://cran.r-project.org/web/packages/gdalUtilities/index.html), with Jonathan Greenberg's *gdalUtils* package (GitHub repo [here](https://github.com/gearslaboratory/gdalUtils/issues)), which he stopped maintaining a while ago, and is currently [archived by CRAN](https://cran.r-project.org/web/packages/gdalUtils/index.html).

Don't quote me on it, but I believe he indicated a while ago that he'd be happy to have somebody take over package maintenance.

Depending on which of the GDAL utilities you use, you may well be able to use my package as a replacement. See the [home page](https://github.com/JoshOBrien/gdalUtilities) for a list of the supported utilities.

**Comment by achubaty** [comment]
Apologies. Must have been combo of confusing the two packages and transient issues trying to install your package.

**Comment by JoshOBrien** [comment]
No problem. You're not the first and won't be the last to mistake one package for the other. Best of luck!
